#!/usr/bin/env python3
import argparse, sys, os, shutil, glob, contextlib, tempfile, socket, stat, secrets, subprocess
from string import Template

import util
from deb import extract_files_from_deb_url
from initramfs import Initramfs
from layers import ContainerStream, dict_to_layer
from qemu import Qemu
from update import update_host

#XXX Add a wrapper around podman/docker build.

#XXX Paramaterize these for the arch/distro/version.
pi_firmware_url=('https://deb.debian.org/debian/pool/non-free/r/raspi-firmware/raspi-firmware_1.20210303+ds-2_arm64.deb',
                 'c828661c47607360a79e51a7b58fb2b0e8f4002c937c2d8d96d276f13badaff2')
uboot_url=('https://deb.debian.org/debian/pool/main/u/u-boot/u-boot-rpi_2021.01+dfsg-5_arm64.deb',
           '67b92cf3efc748f4f724317057af15624b92fbaf0a001e1474c67b9c7483e05b')
busybox_url=('https://deb.debian.org/debian/pool/main/b/busybox/busybox-static_1.30.1-6+b3_arm64.deb',
             '2b27ce9bb8e88f5e30a884397b193420f633dcba1c263e820a0e8f8865bd576c')

mods = [
    'kernel/drivers/regulator/gpio-regulator.ko',
    'kernel/drivers/regulator/fixed.ko',
    'kernel/drivers/mmc/host/sdhci.ko',
    'kernel/drivers/mmc/host/sdhci-pltfm.ko',
    'kernel/drivers/mmc/host/sdhci-iproc.ko',
    'kernel/drivers/mmc/host/bcm2835.ko',
    'kernel/fs/nls/nls_ascii.ko',
    'kernel/fs/nls/nls_cp437.ko',
    'kernel/fs/fat/fat.ko',
    'kernel/fs/fat/vfat.ko',
    'kernel/drivers/block/loop.ko',
    'kernel/fs/squashfs/squashfs.ko',
    'kernel/fs/overlayfs/overlay.ko'
]

scriptroot = os.path.dirname(__file__)
datadir = os.path.join(scriptroot, 'data')

for i in ('tar2sqfs', 'mkenvimage', 'xorriso'):
    if shutil.which(i) is None:
        print('%s is required, but not installed' % i, file=sys.stderr)
        sys.exit(99)

parser = argparse.ArgumentParser(description='Build a server bootdir from a container image.')
parser.add_argument('--hostname', help='hostname of the server')
parser.add_argument('--domain', help='domain name of the server')
parser.add_argument('--no-sshkey', help='don\'t install an ssh auth key for the root user',
                    action='store_true')
parser.add_argument('--cmd', type=str,
                    help='run a different command than the default for this container') #XXX not for --update!
parser.add_argument('--sshport', type=str, default='22',
                    help='update using a non-standard ssh port') #XXX only for --update!

group = parser.add_mutually_exclusive_group(required=True)
group.add_argument('--make-bootable', help='make a bootable starter image in the given directory',
                    type=str)
group.add_argument('--update', help='install the image on an existing server', type=str)
group.add_argument('--run', help='run (in emulation) the bootable image in the given directory', type=str)

args = parser.parse_args()

if args.run:
    qemu = Qemu(args.run, args.cmd)
    qemu.exec()
    assert(False) #qemu_run never returns.

if sys.stdin.isatty():
    print('stdin is a TTY, did you forget to pipe in a tarstream?', file=sys.stderr)
    sys.exit(98)

if args.make_bootable:
    bootdir = args.make_bootable
    slotdir = os.path.join(bootdir, 'slota')
    with contextlib.suppress(FileNotFoundError):
        if len(os.listdir(bootdir)) != 0:
            print("make-bootable output directory isn't empty!", file=sys.stderr)
            sys.exit(97)
        if not os.access(bootdir, os.W_OK | os.X_OK):
            print("make-bootable output directory isn't writable!", file=sys.stderr)
            sys.exit(96)
    layersdir = os.path.join(bootdir, 'layers')
    os.makedirs(layersdir)
    os.makedirs(slotdir)
elif args.update:
    slotdir_obj = tempfile.TemporaryDirectory(prefix='mks_slot_')
    layersdir_obj = tempfile.TemporaryDirectory(prefix='mks_layers_')
    slotdir = slotdir_obj.name
    layersdir = layersdir_obj.name
else:
    assert(False)

#Extract container image info and layers
modtempdir = tempfile.TemporaryDirectory(prefix='mks_mods_')
putasides = [
    ('^boot/config-', (slotdir, True)), ('^boot/System.map-', (slotdir, True)),
    ('^boot/vmlinuz-', (slotdir, True)), ('^boot/initrd.img-', ('', True)),
    ('^usr/lib/linux-image-[^/]+/broadcom/.+', (slotdir, False)),
    ('^run/.+', ('', True)),
    ('^usr/sbin/policy-rc.d', ('', True)), #Debian/Ubuntu container images have this, we remove it.
]
for mod in mods:
    putasides.append(('^lib/modules/[^/]+/%s' % mod, (modtempdir.name, False)))

#XXX Verify that there is a kernel, /boot exists, anything else?
cs = ContainerStream(sys.stdin.buffer, layersdir, putasides)

with open(os.path.join(slotdir, 'layers'), 'w') as layersfile:
    for layer in cs.get_layernames():
        os.makedirs(os.path.join(layersdir, layer), exist_ok=True)
        print(layer, file=layersfile)

arch = cs.get_architecture()

kernelver = glob.glob(os.path.join(slotdir, 'vmlinuz-*'))[0]
kernelver = os.path.split(kernelver)[-1][len('vmlinuz-'):]
with open(os.path.join(slotdir, 'kver.txt'), 'w') as f:
    f.write(kernelver)

#Get hostname/domainname
hostname = args.hostname
if not hostname:
    hostname = cs.get_tags()[0].split(':')[0]
    hostname = hostname.split('/')[1] if '/' in hostname else hostname

domain = args.domain
if not domain:
    domain = socket.getfqdn().split('.', 1)[1]

#Make initramfs
initramfs = Initramfs(busybox_url, os.path.join(datadir, 'init'))
initramfs.copyin(glob.glob(os.path.join(modtempdir.name, '*')), 'mods')
initramfs.write_cpiofile(os.path.join(slotdir, 'initrd.img-%s' % kernelver))

#Generate a finalize/keys/config layer
with open(os.path.join(datadir, 'hosts'), 'r') as f:
    hosts = Template(f.read()).substitute(hostname=hostname, domain=domain)
finalize = {
    'etc/hostname': (hostname + '\n', stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH),
    'etc/hosts': (hosts, stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH),
    'etc/mtab': ('SYMLINK:/proc/mounts', 0),
    'etc/machine-id': (secrets.token_hex(16) + '\n', stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH),
}
#XXX Clobber ssh host keys, if present. /etc/machine-id. /var/lib/systemd/random-seed? Actually need to persist these!

if not args.no_sshkey:
    keyfiles = ('id_ed25519.pub', 'id_rsa.pub')
    keyfiles = [ os.path.expanduser(os.path.join('~', '.ssh', x)) for x in keyfiles ]
    authkeys = []
    for key in keyfiles:
        if os.path.exists(key):
            with open(key, 'r') as kf:
                authkeys.append(kf.read().strip())
    finalize['root/.ssh/authorized_keys'] = ('\n'.join(authkeys) + '\n', stat.S_IRUSR | stat.S_IWUSR)

finalize_layer = os.path.join(slotdir, 'finalize')
dict_to_layer(finalize, finalize_layer)
os.makedirs(finalize_layer, exist_ok=True)

#Copy our scripts into the slotdir's bin/
slotbin = os.path.join(slotdir, 'bin')
os.makedirs(slotbin, exist_ok=True)
shutil.copy(os.path.join(datadir, 'mininit'), slotbin)
shutil.copy(os.path.join(datadir, 'update'), slotbin)

#Finish up. Write whole firmware, or do remote update.
if args.make_bootable:
    if arch == 'arm64':
        util.write_uboot_script(slotdir, 'slota', kernelver)
        shutil.copy(os.path.join(slotdir, 'slotcfg.scr'), bootdir)

        extract_files_from_deb_url(*pi_firmware_url, '^./usr/lib/raspi-firmware/', bootdir)
        extract_files_from_deb_url(*uboot_url, '^./usr/lib/u-boot/rpi_arm64/u-boot.bin', bootdir)

        #Copy u-boot .dtb files into bootdir. Kernel dtbs live in the slotdir.
        for dtb in glob.glob(os.path.join(datadir, 'dtb', '*.dtb')):
            shutil.copy(dtb, bootdir)

        shutil.copy(os.path.join(datadir, 'config.txt'), bootdir)
        with open(os.path.join(bootdir, 'uboot.env'), 'wb') as f:
            subprocess.Popen(['mkenvimage', '-o-', '-s16384', '-p0', os.path.join(datadir, 'ubootenv.txt')],
                             stdout=f)

        if args.cmd:
            cmd = args.cmd
        else:
            cmd = util.posix_list2cmdline(cs.get_cmdlist())
        with open(os.path.join(bootdir, 'initcmd.txt'), 'w') as f:
            f.write(cmd)
    else:
        assert(False) #XXX xorriso for amd64.
elif args.update:
    update_host(slotdir, layersdir, args.update, args.sshport)

print('\nBuilt %s.%s for arch %s' % (hostname, domain, arch))
