#!/bin/sh

#XXX Does any of mounting /sys, /tmp or /run get done by systemd itself?
mount -oremount,rw /dev
mkdir /dev/pts
mount -oremount,ro /dev
TTYGID=`grep ^tty: /etc/group | cut -d':' -f3`
mount devpts /dev/pts -t devpts -o ro,nosuid,noexec,gid=$TTYGID,mode=620,ptmxmode=000

#Networking
#XXX Support wifi too
modprobe -a rndis_host dwc2

IFACE=eth0
#XXX Support static IPs too
dhclient -4 -I -nw -lf /run/dhclient.$IFACE.leases $IFACE

#Start sshd for rootslot updates
mkdir -p /run/sshd
chmod 0755 /run/sshd
`which sshd`
